# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/001_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/001_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/002_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/002_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/003_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/003_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/004_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/004_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/005_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/005_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/006_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/006_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/007_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/007_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/008_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/008_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/009_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/009_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/010_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/010_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/011_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/011_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/012_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/012_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/013_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/013_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/01_tagging/014_tagging --output_path /gemini/user/private/3D/data/egohumans/01_tagging/014_tagging/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/02_lego/001_legoassemble --output_path /gemini/user/private/3D/data/egohumans/02_lego/001_legoassemble/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/02_lego/002_legoassemble --output_path /gemini/user/private/3D/data/egohumans/02_lego/002_legoassemble/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/02_lego/003_legoassemble --output_path /gemini/user/private/3D/data/egohumans/02_lego/003_legoassemble/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/02_lego/004_legoassemble --output_path /gemini/user/private/3D/data/egohumans/02_lego/004_legoassemble/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/02_lego/005_legoassemble --output_path /gemini/user/private/3D/data/egohumans/02_lego/005_legoassemble/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/02_lego/006_legoassemble --output_path /gemini/user/private/3D/data/egohumans/02_lego/006_legoassemble/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/001_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/001_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/002_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/002_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/003_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/003_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/004_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/004_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/005_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/005_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/006_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/006_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/007_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/007_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/008_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/008_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/009_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/009_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/010_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/010_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/011_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/011_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/012_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/012_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/013_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/013_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/03_fencing/014_fencing --output_path /gemini/user/private/3D/data/egohumans/03_fencing/014_fencing/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/001_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/001_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/002_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/002_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/003_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/003_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/004_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/004_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/005_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/005_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/006_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/006_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/007_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/007_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/008_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/008_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/009_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/009_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/010_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/010_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/011_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/011_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/012_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/012_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/013_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/013_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/04_basketball/014_basketball --output_path /gemini/user/private/3D/data/egohumans/04_basketball/014_basketball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/001_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/001_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/002_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/002_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/003_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/003_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/004_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/004_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/005_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/005_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/006_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/006_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/007_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/007_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/008_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/008_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/009_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/009_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/010_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/010_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/05_volleyball/011_volleyball --output_path /gemini/user/private/3D/data/egohumans/05_volleyball/011_volleyball/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/001_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/001_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/002_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/002_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/003_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/003_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/004_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/004_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/005_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/005_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/006_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/006_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/007_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/007_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/008_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/008_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/009_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/009_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/010_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/010_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/011_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/011_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/012_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/012_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/013_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/013_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/014_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/014_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/015_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/015_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/016_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/016_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/017_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/017_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/018_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/018_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/019_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/019_badminton/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/020_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/020_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/021_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/021_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/022_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/022_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/023_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/023_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/024_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/024_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/025_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/025_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/026_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/026_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/027_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/027_badminton/data_para     
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/028_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/028_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/029_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/029_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/030_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/030_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/031_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/031_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/032_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/032_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/033_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/033_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/034_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/034_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/035_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/035_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/036_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/036_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/037_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/037_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/038_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/038_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/039_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/039_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/040_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/040_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/041_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/041_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/042_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/042_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/043_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/043_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/044_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/044_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/045_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/045_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/046_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/046_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/047_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/047_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/048_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/048_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/049_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/049_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/050_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/050_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/051_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/051_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/052_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/052_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/053_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/053_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/054_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/054_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/055_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/055_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/056_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/056_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/057_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/057_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/058_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/058_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/059_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/059_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/060_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/060_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/06_badminton/061_badminton --output_path /gemini/user/private/3D/data/egohumans/06_badminton/061_badminton/data_para
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/001_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/001_tennis/data_para 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/002_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/002_tennis/data_para --max_frames 1039 
python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/003_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/003_tennis/data_para --max_frames 1084 
python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/004_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/004_tennis/data_para --max_frames 1095
python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/006_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/006_tennis/data_para --max_frames 986 
python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/007_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/007_tennis/data_para --max_frames 1081 
python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/008_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/008_tennis/data_para --max_frames 1084 
python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/009_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/009_tennis/data_para --max_frames 1081 
python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/010_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/010_tennis/data_para --max_frames 1056 
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/011_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/011_tennis/data_para
python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/012_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/012_tennis/data_para --max_frames 1035
# python merge_dataset_save.py --root_path /gemini/user/private/3D/data/EgoHumans/07_tennis/013_tennis --output_path /gemini/user/private/3D/data/egohumans/07_tennis/013_tennis/data_para 
